# Docker compose file for Wyoming-Piper (TTS) instance. Required for vCHAOS backend
# Sourced from https://github.com/slackr31337/wyoming-piper-gpu
# Should be run from the /setup/docker directory.

services:
  piper-gpu:
    container_name: piper-gpu
    image: ghcr.io/slackr31337/wyoming-piper-gpu:latest
    ports:
      - 10200:10200
    volumes:
      - ../../src/data:/data
      - ../../src/tmp:/tmp
      - ../../src/output:/output
      - ../../src/settings.yaml:/settings.yaml
      - ../../src/handler.py:/usr/local/lib/python3.10/dist-packages/wyoming_piper/handler.py
      - ../../src/handler.py:/app/lib/python3.10/site-packages/wyoming_piper/handler.py
    restart: always
    command: --voice en_US-amy-medium 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]