app:
  host: "0.0.0.0"   # Host address (use 0.0.0.0 for LAN access; or 127.0.0.1 for host machine access only) // Default: 0.0.0.0
  port: 11405       # Port number for the web server (can be any unassigned port) // Default: 11405

logging:
  level: "ERROR"      # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL) // Default: ERROR